
<?php
    
    /* course_conversion_look_up.php
     *
     * look up table - new course/ prefix code conversion table
     * from website: https://www.uml.edu/Registrar/Policies-and-Procedures/Course-Master-Schedule-Info/subject-prefix-code.aspx
     */
    

  $look_up_subject_code = array(
                                  10 => "CHEN",
                                  14 => "CIVE",
                                  16 => "EECE",
                                  17 => "ETEC",
                                  18 => "ENVS",
                                  19 => "PUBH",
                                  22 => "MECH",
                                  23 => "MTEC",
                                  24 => "ENGY",
                                  25 => "ENGN",
                                  26 => "PLAS",
                                  27 => "PETC",
                                  28 => "ROTC",
                                  29 => "AERO",
                                  30 => "HSCI",
                                  31 => "PUBH",
                                  32 => "PUBH",
                                  33 => "NURS",
                                  34 => "DPTH",
                                  35 => "HSCI",
                                  36 => "MLSC",
                                  38 => "EXER",
                                  40 => "AMST",
                                  41 => "LGST",
                                  42 => "ENGL",
                                  43 => "HIST",
                                  44 => "CRIM",
                                  45 => "PHIL",
                                  46 => "POLI",
                                  47 => "PSYC",
                                  48 => "SOCI",
                                  49 => "ECON",
                                  50 => "WLFR",
                                  51 => "WLGE",
                                  52 => "WLIT",
                                  53 => "WLKH",
                                  54 => "WLSP",
                                  56 => "WLLA",
                                  58 => "ARHI",
                                  59 => "FAHS",
                                  60 => "ACCT",
                                  61 => "FINA",
                                  62 => "MKTG",
                                  63 => "POMS",
                                  64 => "ENTR",
                                  66 => "MGMT",
                                  69 => "BUSI",
                                  70 => "ARTS",
                                  71 => "MUTH",
                                  72 => "MUAP",
                                  73 => "MUED",
                                  74 => "MUHI",
                                  75 => "MUPF",
                                  76 => "MUEN",
                                  77 => "MUBU",
                                  78 => "MUSR",
                                  79 => "ASET",
                                  81 => "BIOL",
                                  82 => "SCIE",
                                  83 => "LIFE",
                                  84 => "CHEM",
                                  85 => "ATMO",
                                  87 => "ENVI",
                                  89 => "GEOL",
                                  90 => "INFO",
                                  91 => "COMP",
                                  92 => "MATH",
                                  94 => "MSIT",
                                  95 => "PHYS",
                                  96 => "PHYSl",
                                  97 => "POLY",
                                  98 => "RADI",
                                  99 => "RADIl",
                                  "CM" => "CONT",
                                  "HON" => "HONR",
                                  "IB" => "BMBT",
                                  "IM" => "MARI",
                                  "NC" => "NONC",
                                  "PCS" => "PCST",
                                  "PHSC" => "PHRM",
                                  "PSM" => "PSMA",
                                  "UTL" => "UTCH",
                                  "WLS" => "LABR"
                                  );

?>
